services:
  db:
    image: postgres:16
    container_name: gachita-db
    environment:
      POSTGRES_USER: gachita
      POSTGRES_PASSWORD: gachita
      POSTGRES_DB: gachita
    ports:
      - "5434:5432"
    volumes:
      - gachita_pgdata:/var/lib/postgresql/data

volumes:
  gachita_pgdata: