// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hub_stop.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHubStop = `-- name: CreateHubStop :one
INSERT INTO hub_stops (room_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, room_id, name, sort_order, created_at
`

type CreateHubStopParams struct {
	RoomID    pgtype.UUID
	Name      string
	SortOrder int32
}

func (q *Queries) CreateHubStop(ctx context.Context, arg CreateHubStopParams) (HubStop, error) {
	row := q.db.QueryRow(ctx, createHubStop, arg.RoomID, arg.Name, arg.SortOrder)
	var i HubStop
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHubStop = `-- name: DeleteHubStop :one
DELETE FROM hub_stops
WHERE id = $1 AND room_id = $2
RETURNING id, room_id, name, sort_order, created_at
`

type DeleteHubStopParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
}

func (q *Queries) DeleteHubStop(ctx context.Context, arg DeleteHubStopParams) (HubStop, error) {
	row := q.db.QueryRow(ctx, deleteHubStop, arg.ID, arg.RoomID)
	var i HubStop
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getHubStopByID = `-- name: GetHubStopByID :one
SELECT id, room_id, name, sort_order, created_at FROM hub_stops WHERE id = $1
`

func (q *Queries) GetHubStopByID(ctx context.Context, id pgtype.UUID) (HubStop, error) {
	row := q.db.QueryRow(ctx, getHubStopByID, id)
	var i HubStop
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listHubStopsByRoomID = `-- name: ListHubStopsByRoomID :many
SELECT id, room_id, name, sort_order, created_at FROM hub_stops
WHERE room_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListHubStopsByRoomID(ctx context.Context, roomID pgtype.UUID) ([]HubStop, error) {
	rows, err := q.db.Query(ctx, listHubStopsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubStop
	for rows.Next() {
		var i HubStop
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHubStop = `-- name: UpdateHubStop :one
UPDATE hub_stops
SET name = $3, sort_order = $4
WHERE id = $1 AND room_id = $2
RETURNING id, room_id, name, sort_order, created_at
`

type UpdateHubStopParams struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateHubStop(ctx context.Context, arg UpdateHubStopParams) (HubStop, error) {
	row := q.db.QueryRow(ctx, updateHubStop,
		arg.ID,
		arg.RoomID,
		arg.Name,
		arg.SortOrder,
	)
	var i HubStop
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
