// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMatchMember = `-- name: AddMatchMember :exec
INSERT INTO match_members (match_id, user_id, queue_entry_id)
VALUES ($1, $2, $3)
`

type AddMatchMemberParams struct {
	MatchID      pgtype.UUID
	UserID       pgtype.UUID
	QueueEntryID pgtype.UUID
}

func (q *Queries) AddMatchMember(ctx context.Context, arg AddMatchMemberParams) error {
	_, err := q.db.Exec(ctx, addMatchMember, arg.MatchID, arg.UserID, arg.QueueEntryID)
	return err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (room_id)
VALUES ($1)
RETURNING id, room_id, status, created_at
`

func (q *Queries) CreateMatch(ctx context.Context, roomID pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, roomID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, room_id, status, created_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchCandidates = `-- name: ListMatchCandidates :many
SELECT id, room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats, status, created_at FROM queue_entries
WHERE room_id = $1
  AND from_stop_id = $2
  AND to_stop_id = $3
  AND status = 'waiting'
  AND time_start < $4
  AND time_end > $5
ORDER BY created_at
`

type ListMatchCandidatesParams struct {
	RoomID     pgtype.UUID
	FromStopID pgtype.UUID
	ToStopID   pgtype.UUID
	TimeStart  pgtype.Timestamptz
	TimeEnd    pgtype.Timestamptz
}

func (q *Queries) ListMatchCandidates(ctx context.Context, arg ListMatchCandidatesParams) ([]QueueEntry, error) {
	rows, err := q.db.Query(ctx, listMatchCandidates,
		arg.RoomID,
		arg.FromStopID,
		arg.ToStopID,
		arg.TimeStart,
		arg.TimeEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueEntry
	for rows.Next() {
		var i QueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.FromStopID,
			&i.ToStopID,
			&i.TimeStart,
			&i.TimeEnd,
			&i.MinSeats,
			&i.MaxSeats,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchMembersByMatchID = `-- name: ListMatchMembersByMatchID :many
SELECT
  mm.match_id,
  mm.user_id,
  mm.queue_entry_id,
  u.nickname,
  qe.from_stop_id,
  qe.to_stop_id,
  qe.time_start,
  qe.time_end
FROM match_members mm
JOIN users u ON u.id = mm.user_id
JOIN queue_entries qe ON qe.id = mm.queue_entry_id
WHERE mm.match_id = $1
`

type ListMatchMembersByMatchIDRow struct {
	MatchID      pgtype.UUID
	UserID       pgtype.UUID
	QueueEntryID pgtype.UUID
	Nickname     string
	FromStopID   pgtype.UUID
	ToStopID     pgtype.UUID
	TimeStart    pgtype.Timestamptz
	TimeEnd      pgtype.Timestamptz
}

func (q *Queries) ListMatchMembersByMatchID(ctx context.Context, matchID pgtype.UUID) ([]ListMatchMembersByMatchIDRow, error) {
	rows, err := q.db.Query(ctx, listMatchMembersByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchMembersByMatchIDRow
	for rows.Next() {
		var i ListMatchMembersByMatchIDRow
		if err := rows.Scan(
			&i.MatchID,
			&i.UserID,
			&i.QueueEntryID,
			&i.Nickname,
			&i.FromStopID,
			&i.ToStopID,
			&i.TimeStart,
			&i.TimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByRoomID = `-- name: ListMatchesByRoomID :many
SELECT id, room_id, status, created_at FROM matches
WHERE room_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMatchesByRoomID(ctx context.Context, roomID pgtype.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueueEntriesMatched = `-- name: MarkQueueEntriesMatched :exec
UPDATE queue_entries
SET status = 'matched'
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkQueueEntriesMatched(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markQueueEntriesMatched, dollar_1)
	return err
}
