// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HubStop struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type Match struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
}

type MatchMember struct {
	MatchID      pgtype.UUID
	UserID       pgtype.UUID
	QueueEntryID pgtype.UUID
}

type QueueEntry struct {
	ID         pgtype.UUID
	RoomID     pgtype.UUID
	UserID     pgtype.UUID
	FromStopID pgtype.UUID
	ToStopID   pgtype.UUID
	TimeStart  pgtype.Timestamptz
	TimeEnd    pgtype.Timestamptz
	MinSeats   int32
	MaxSeats   int32
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type Room struct {
	ID          pgtype.UUID
	Name        string
	InviteCode  string
	OpenchatUrl pgtype.Text
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMember struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Nickname     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
