// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HubStop struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type Room struct {
	ID          pgtype.UUID
	Name        string
	InviteCode  string
	OpenchatUrl pgtype.Text
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMember struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Nickname     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
