// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package db

import (
	"context"
)

const pingTest = `-- name: PingTest :one
SELECT 1::int AS ok
`

func (q *Queries) PingTest(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingTest)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
