// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_entry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueueEntry = `-- name: CancelQueueEntry :one
UPDATE queue_entries
SET status = 'cancelled'
WHERE id = $1 AND room_id = $2 AND user_id = $3 AND status = 'waiting'
RETURNING id, room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats, status, created_at
`

type CancelQueueEntryParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CancelQueueEntry(ctx context.Context, arg CancelQueueEntryParams) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, cancelQueueEntry, arg.ID, arg.RoomID, arg.UserID)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.FromStopID,
		&i.ToStopID,
		&i.TimeStart,
		&i.TimeEnd,
		&i.MinSeats,
		&i.MaxSeats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createQueueEntry = `-- name: CreateQueueEntry :one
INSERT INTO queue_entries (room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats, status, created_at
`

type CreateQueueEntryParams struct {
	RoomID     pgtype.UUID
	UserID     pgtype.UUID
	FromStopID pgtype.UUID
	ToStopID   pgtype.UUID
	TimeStart  pgtype.Timestamptz
	TimeEnd    pgtype.Timestamptz
	MinSeats   int32
	MaxSeats   int32
}

func (q *Queries) CreateQueueEntry(ctx context.Context, arg CreateQueueEntryParams) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, createQueueEntry,
		arg.RoomID,
		arg.UserID,
		arg.FromStopID,
		arg.ToStopID,
		arg.TimeStart,
		arg.TimeEnd,
		arg.MinSeats,
		arg.MaxSeats,
	)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.FromStopID,
		&i.ToStopID,
		&i.TimeStart,
		&i.TimeEnd,
		&i.MinSeats,
		&i.MaxSeats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getQueueEntryByID = `-- name: GetQueueEntryByID :one
SELECT id, room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats, status, created_at FROM queue_entries WHERE id = $1
`

func (q *Queries) GetQueueEntryByID(ctx context.Context, id pgtype.UUID) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, getQueueEntryByID, id)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.FromStopID,
		&i.ToStopID,
		&i.TimeStart,
		&i.TimeEnd,
		&i.MinSeats,
		&i.MaxSeats,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitingQueueEntriesByRoomID = `-- name: ListWaitingQueueEntriesByRoomID :many
SELECT id, room_id, user_id, from_stop_id, to_stop_id, time_start, time_end, min_seats, max_seats, status, created_at FROM queue_entries
WHERE room_id = $1 AND status = 'waiting'
ORDER BY created_at
`

func (q *Queries) ListWaitingQueueEntriesByRoomID(ctx context.Context, roomID pgtype.UUID) ([]QueueEntry, error) {
	rows, err := q.db.Query(ctx, listWaitingQueueEntriesByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueEntry
	for rows.Next() {
		var i QueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.FromStopID,
			&i.ToStopID,
			&i.TimeStart,
			&i.TimeEnd,
			&i.MinSeats,
			&i.MaxSeats,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
