// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, invite_code, openchat_url, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, invite_code, openchat_url, owner_id, created_at, updated_at
`

type CreateRoomParams struct {
	Name        string
	InviteCode  string
	OpenchatUrl pgtype.Text
	OwnerID     pgtype.UUID
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.InviteCode,
		arg.OpenchatUrl,
		arg.OwnerID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.OpenchatUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, invite_code, openchat_url, owner_id, created_at, updated_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.OpenchatUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByInviteCode = `-- name: GetRoomByInviteCode :one
SELECT id, name, invite_code, openchat_url, owner_id, created_at, updated_at FROM rooms WHERE invite_code = $1
`

func (q *Queries) GetRoomByInviteCode(ctx context.Context, inviteCode string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByInviteCode, inviteCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.OpenchatUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomsByUserID = `-- name: ListRoomsByUserID :many
SELECT r.id, r.name, r.invite_code, r.openchat_url, r.owner_id, r.created_at, r.updated_at
FROM rooms r
JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
ORDER BY rm.joined_at DESC
`

func (q *Queries) ListRoomsByUserID(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.OpenchatUrl,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
