// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :one
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
RETURNING room_id, user_id, joined_at
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, addRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(&i.RoomID, &i.UserID, &i.JoinedAt)
	return i, err
}

const getRoomMember = `-- name: GetRoomMember :one
SELECT room_id, user_id, joined_at FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type GetRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetRoomMember(ctx context.Context, arg GetRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(&i.RoomID, &i.UserID, &i.JoinedAt)
	return i, err
}

const listRoomMembersByRoomID = `-- name: ListRoomMembersByRoomID :many
SELECT room_id, user_id, joined_at FROM room_members WHERE room_id = $1
`

func (q *Queries) ListRoomMembersByRoomID(ctx context.Context, roomID pgtype.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listRoomMembersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(&i.RoomID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembersWithUser = `-- name: ListRoomMembersWithUser :many
SELECT
  rm.room_id,
  rm.user_id,
  rm.joined_at,
  u.nickname,
  u.email
FROM room_members rm
JOIN users u ON u.id = rm.user_id
WHERE rm.room_id = $1
ORDER BY rm.joined_at
`

type ListRoomMembersWithUserRow struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
	Nickname string
	Email    string
}

func (q *Queries) ListRoomMembersWithUser(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembersWithUser, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersWithUserRow
	for rows.Next() {
		var i ListRoomMembersWithUserRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.JoinedAt,
			&i.Nickname,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
